server:
  port: 5141
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.200:3307/damai_clothing?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: '&6QtQJN*MCCt@56'
#    url: jdbc:mysql://61.160.251.58:3306/damai_clothing?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
#    username: root
#    password: '.3rsL,6@#oXeIY'
  redis:
    database: 1
    host: 192.168.0.200
    port: 6378
    password: slfaljkhflaij140gna
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  freemarker:
    suffix: .html
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  rabbitmq:
#    host: 192.168.0.200
#    port: 5682
#    username: admin
#    password: qkmbous^13a!
#    virtual-host: /damai-clothing
#    listener:
#      simple:
#        acknowledge-mode: manual #设置确认模式手工确认
#        concurrency: 3 #消费者最小数量
#        max-concurrency: 10 # 消费者最大数量
mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.fenglei.model
minio:
  view-endpoint: https://zhkc.jsflems.com:8123/minio/
  endpoint: http://192.168.0.200:9001/
  access-key: root
  secret-key: asjflsajlkaj1afja
  bucket: damai-clothing
wechat:
  weapp:
    appid: wx4501e37495a52cf9
    secret: a83cf7b89677075e2f5be2b8c2dad234
project-params:
  default-customer-avatar: ${minio.view-endpoint}${minio.bucket}/assests/defaultImg.png
order:
  cancelTime: 30
